name: 'auto release'
on:
  pull_request:
    types:
      - closed

jobs:
  trigger_release_job:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: Trigger Release Job
    steps:
      - name: Trigger Release
        env:
          REPO_ACCESS_TOKEN: ${{ secrets.GH_TOKEN }}
      # Send the repository_dispatch event using curl
      - name: Dispatch Release
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $REPO_ACCESS_TOKEN" \
            -d "{}" \  # Empty payload, no variables to send
            "https://api.github.com/repos/fivetran-catfritz/release-creator/dispatches"