name: 'auto release'
on:
  pull_request:
    types:
      - closed

jobs:
  call-workflow-passing-data:
    uses: fivetran-catfritz/release-creator/.github/workflows/auto-release.yml@main
    secrets: inherit