name: 'auto release'
on:
  pull_request:
    types:
      - closed

jobs:
  update:
    # if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    name: Trigger Release Job
    steps:
      - name: Trigger Release
        uses: fivetran-catfritz/release-creator@v0.1.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: fivetran-catfritz/release-creator
          event-type: trigger_release