name: 'auto release'
on:
  pull_request:
    types:
      - closed

jobs:
  update:
    runs-on: ubuntu-latest
    name: Create a release
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract version from changelog
        id: extract_version
        run: |
          # Use appropriate commands to extract the version number from the changelog file
          # For example, you can use grep or awk to extract the version from the first row.
          VERSION=$(grep -oP 'v[0-9]+.*' CHANGELOG.md | head -1)
          echo "Extracted version: $VERSION"
          echo "::set-output name=version::$VERSION"
          
      - name: Create Release
        uses: alice-biometrics/release-creator/@v1.0.5
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          version: ${{ steps.extract_version.outputs.version }}
          description: 'This is an awesome version :ok_hand:'
          repo: ${{ github.repository }}
          branch: 'main'
          draft: 'true'
          prerelease: 'false'